[[redirects]]
  from = "/api/quote"
  to = "/api/quote.js"
  status = 200

[[redirects]]
  from = "/api/indices"
  to = "/api/indices.js"
  status = 200

[[redirects]]
  from = "/api/all"
  to = "/api/all.js"
  status = 200

[[redirects]]
  from = "/api/news"
  to = "/api/news.js"
  status = 200
